name: Deploy to Jagoan Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository@v2.1.0
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 10

    - name: Copy .gitignore
      run: cp .gitignore .gitignore_temp

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'

    - name: Install dependencies, build assets, and deploy
      run: |
        sudo apt-get install ftp -y
        npm run build

    - name: Compress files
      run: zip -r main.zip .

    - name: Upload to Hosting
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        remote-dir: /home/sacpocom/data-center.sac-po.com/sac
